version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: blog
    container_name: mydb

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  server:
    build: ./server/
    depends_on:
      - db
    ports:
      - '4000:4000'
    container_name: server
    environment:
      PORT: 4000
      NODE_ENV: production
      DB_HOST: mydb
      DB_USER: root
      DB_PASSWORD: 12345678
      DB_NAME: blog

  web:
    build: ./web/
    ports:
      - '3000:3000'
    container_name: web
    environment:
      PORT: 3000
      API_URL: http://server:4000
      NEXT_PUBLIC_OSS_accessKeyId: xxxx
      NEXT_PUBLIC_OSS_accessKeySecret: xxxx
      NEXT_PUBLIC_OSS_region: oss-cn-hangzhou
      NEXT_PUBLIC_OSS_bucket: xxxx
      NEXT_PUBLIC_OSS_endpoint: http://oss.example.cn

  nginx:
    image: "nginx:alpine"
    ports:
      - '8082:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  default:
    driver: bridge
